In [ ]:
# Addition.ipynb

In [1]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [2]:
b=np.array([[7,8],[9,10],[11,12]])
print(b)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [3]:
c=a+b
print(c)

[[ 8 10]
 [12 14]
 [16 18]]
