In [1]:
#feedforword.ipynb

x:
[[10]
 [ 7]
 [ 3]]


In [ ]:
import numpy as np
x=np.array([[10],[7],[3]])
print(x)

In [2]:
w1=np.zeros((2,3))
w1[0]=[-7,4,14]
w1[1]=[4,-6,3]
print(w1)

[[ -7.   4.  14.]
 [  4.  -6.   3.]]


In [3]:
u=w1.dot(x)
print(u)

[[ 0.]
 [ 7.]]


In [4]:
b=np.array([-0.6,-0.3])
print(b)

[-0.6 -0.3]


In [5]:
b=np.reshape(b,(1,2))
print(b)

[[-0.6 -0.3]]


In [6]:
b=b.T
print(b)

[[-0.6]
 [-0.3]]


In [7]:
z1=u+b
print(z1)

[[-0.6]
 [ 6.7]]


In [8]:
def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))

a1=sigmoid(z1)
print(a1)

[[ 0.35434369]
 [ 0.9987706 ]]


In [9]:
w2=np.array([[4,5]])
print(w2)

[[4 5]]


In [10]:
u2=w2.dot(a1)
print(u2)

[[ 6.41122778]]


In [11]:
b2=np.array([[-6]])
print(b2)

[[-6]]


In [12]:
z2=u2+b2
print(z2)

[[ 0.41122778]]


In [13]:
a2=sigmoid(z2)
print(a2)

[[ 0.60138224]]
