In [2]:
#Transpose.ipynb

In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("a.shape =",a.shape)
print(a)


a.shape = (2, 3)
[[1 2 3]
 [4 5 6]]


In [9]:
b=a.T
print("b.shape = ",b.shape)
print(b)


b.shape =  (3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [15]:
c=np.array([1,2,3])
print("c.shape = ",c.shape)
print(c)

c.shape (3,)
[1 2 3]


In [16]:
d=c.T
print("d.shape = ",d.shape)
print(d)

d.shape (3,)
[1 2 3]


In [19]:
e=np.array([[1,2,3]])
print("e.shape = ",e.shape)
print(e)

e.shape =  (1, 3)
[[1 2 3]]


In [20]:
f=e.T
print("f.shape = ",f.shape)
print(f)

f.shape =  (3, 1)
[[1]
 [2]
 [3]]
